spring:
  cloud:
    stream:
      bindings:
        input:
          destination: queue.log.messages
          binder: rabbit
        output:
          destination: queue.pretty.log.messages
          binder: rabbit
  security:
    user:
      name: admin
      password: solace1
server:
  port: 8888